### ISSUE TITLE
Maybe a bug in visualisation utils

### ISSUE THREAD

**Issue by hejujie** [waterhorse1/NAC#1]
https://github.com/waterhorse1/NAC/blob/dd355a9d53909470c7e26fb8a7ee7380ea2bb02a/2d-rps-gradient/visualisation/utils/best_responder.py#L104
I didn't deep into the code, but maybe a bug ? mus -> mu ?
![image](https://user-images.githubusercontent.com/29149911/142007627-2cad99e5-2c6e-43ce-83de-312a950c271f.png)

**Comment by hejujie** [comment]
Also agent1, agent2 in: https://github.com/waterhorse1/NAC/blob/dd355a9d53909470c7e26fb8a7ee7380ea2bb02a/2d-rps-gradient/visualisation/utils/best_responder.py#L65

**Comment by waterhorse1** [comment]
Hi,

Thank you for pointing that out. I find out because of the .gitignore I fail to upload the jupyter notebook to github and now I have fixed this problem.

And the bug you point out is our previous wrong implementation and I forget to remove it. You can check out the new jupyter notebook to see that we haven't use that code. And you can refer to the right implicit_best_responder function here:

https://github.com/waterhorse1/NAC/blob/5a7dbfae754ad99d00a52df5826eb57121fa1d21/2d-rps-implicit/environments/gmm_rps.py#L321

**Comment by hejujie** [comment]
get it, I will close the issue;
